/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/artifacts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Lists stored artifact keys, each with its newest version. */
    get: operations["listArtifacts"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/artifacts/{key}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Returns one artifact key with its newest version. */
    get: operations["getArtifact"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/artifacts/{key}/versions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Lists the stored versions of an artifact. */
    get: operations["listArtifactVersions"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/artifacts/{key}/versions/{digest}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Returns one stored version. */
    get: operations["getArtifactVersion"];
    put?: never;
    post?: never;
    /** Evicts one stored version and its blob, if no other version needs it. */
    delete: operations["deleteArtifactVersion"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/logs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Lists log events with optional filtering. */
    get: operations["listLogs"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/logs/boots": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Lists distinct boot sessions, newest first. */
    get: operations["listLogBoots"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/logs/spans": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Lists tracing spans with optional filtering. */
    get: operations["listSpans"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/logs/spans/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Returns a single span with its events. */
    get: operations["getSpan"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/logs/targets": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Lists distinct log targets for autocomplete. */
    get: operations["listLogTargets"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/task-definitions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Lists the registered task kinds with their capabilities and JSON Schemas. */
    get: operations["listTaskDefinitions"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/tasks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Lists task invocations, optionally filtered by status, kind, and parent.
     *     Running tasks carry live progress.
     */
    get: operations["listTasks"];
    put?: never;
    /**
     * Creates a task of the given kind and starts it. The body input is validated
     *     against the kind's input schema.
     */
    post: operations["createTask"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/tasks/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Returns one task invocation. */
    get: operations["getTask"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/tasks/{id}/cancel": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Requests cooperative cancellation of a running task. */
    post: operations["cancelTask"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/version": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Returns version information about the gateway. */
    get: operations["getGatewayVersion"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * @description A distinct artifact key with its newest version, for `GET
     *     /api/v1/artifacts`.
     */
    ArtifactSummaryResponse: {
      /** @description Content digest of the newest version. */
      digest: string;
      /**
       * Format: date-time
       * @description When the newest version was downloaded.
       */
      downloaded_at: string;
      /** @description Logical artifact key. */
      key: string;
      /**
       * Format: int64
       * @description Stored blob size of the newest version, in bytes.
       */
      size_bytes: number;
      /** @description Where the newest version came from. */
      source: string;
      /** @description Human-readable version of the newest version, if known. */
      version?: string | null;
      /**
       * Format: int64
       * @description How many versions of this key are stored.
       */
      version_count: number;
    };
    /** @description One stored version of an artifact. */
    ArtifactVersionResponse: {
      /** @description Content digest of the stored blob. */
      digest: string;
      /**
       * Format: date-time
       * @description When this version was downloaded.
       */
      downloaded_at: string;
      /** @description Logical artifact key. */
      key: string;
      /** @description OCI media type, if applicable. */
      media_type?: string | null;
      /**
       * Format: int64
       * @description Stored blob size in bytes.
       */
      size_bytes: number;
      /** @description Where this version came from. */
      source: string;
      /**
       * Format: date-time
       * @description When this version was last verified, if ever.
       */
      verified_at?: string | null;
      /** @description Human-readable version, if known. */
      version?: string | null;
    };
    /**
     * @description One boot session observed in the log store, returned by
     *     `GET /api/v1/logs/boots`.
     */
    BootResponse: {
      /**
       * Format: uuid
       * @description Unique boot id (UUID).
       */
      boot_id: string;
      /**
       * Format: int64
       * @description Number of events recorded so far in this boot.
       */
      event_count: number;
      /**
       * Format: date-time
       * @description Timestamp of the earliest event in this boot.
       */
      first_seen: string;
      /** @description True if this is the currently running gateway boot. */
      is_current: boolean;
      /**
       * Format: date-time
       * @description Timestamp of the latest event in this boot.
       */
      last_seen: string;
    };
    CreateTaskInput: {
      input: components["schemas"]["DownloadInput"];
      /** @enum {string} */
      kind: "download";
    };
    /** @description Body for `POST /api/v1/tasks`. */
    CreateTaskRequest: {
      /** @description The task input, matching the kind's input schema. */
      input: unknown;
      /** @description The kind of task to create. */
      kind: string;
    };
    /**
     * @description Primary key of a row in the database (SQLite rowid).
     *
     *     Wraps an [`i64`] so that parsing and display are centralized on the type
     *     itself rather than scattered as free functions. Serializes as a string to
     *     keep the API representation opaque.
     */
    DbId: string;
    /** @description Input for a download task: what to fetch and where from. */
    DownloadInput: {
      /** @description Logical key to record the artifact under. */
      key: string;
      /** @description Where and how to fetch it from. */
      source: components["schemas"]["DownloadSource"];
    };
    /** @description Output of a download task: the stored version that resulted. */
    DownloadOutput: {
      /** @description Content digest of the stored blob. */
      digest: string;
      /**
       * Format: int64
       * @description Stored blob size in bytes.
       */
      size_bytes: number;
      /** @description Human-readable version, if known. */
      version?: string | null;
    };
    /** @description Where a download fetches from. */
    DownloadSource: {
      /** @description The media type of the layer to pull. */
      media_type: string;
      /** @description The image reference, for example `ghcr.io/org/image:tag`. */
      reference: string;
      /** @enum {string} */
      type: "oci";
    };
    /**
     * @description A structured field filter passed as a string-encoded JSON object in a
     *     query parameter, e.g. `{"key":"value"}`. The raw string is parsed into
     *     key-value pairs during deserialization.
     * @example {"status":"ok"}
     */
    JsonQueryString: string;
    /**
     * @description Severity level of a log event or span.
     * @enum {string}
     */
    LevelResponse: "trace" | "debug" | "info" | "warn" | "error";
    /** @description A single log event, returned by `GET /api/v1/logs`. */
    LogEventResponse: {
      /**
       * Format: uuid
       * @description Boot session this event belongs to, if known.
       */
      boot_id: string;
      /** @description Structured fields as a JSON object, if any. */
      fields: {
        [key: string]: unknown;
      };
      /** @description Source file, if available. */
      file?: string | null;
      /** @description Event id. */
      id: components["schemas"]["DbId"];
      /** @description Severity level. */
      level: components["schemas"]["LevelResponse"];
      /**
       * Format: int32
       * @description Source line, if available.
       */
      line?: number | null;
      /** @description Human-readable message, if any. */
      message?: string | null;
      span_id?: null | components["schemas"]["DbId"];
      /** @description Module path that emitted the event. */
      target: string;
      /**
       * Format: date-time
       * @description When the event was emitted.
       */
      timestamp: string;
    };
    /** @description A span with its child events, returned by `GET /api/v1/logs/spans/{id}`. */
    LogSpanDetailResponse: components["schemas"]["LogSpanResponse"] & {
      /** @description Events belonging to this span, ordered by timestamp. */
      events: components["schemas"]["LogEventResponse"][];
    };
    /** @description A tracing span, returned by `GET /api/v1/logs/spans`. */
    LogSpanResponse: {
      /**
       * Format: date-time
       * @description When the span ended, if it did.
       */
      ended_at?: string | null;
      /** @description Span fields as a JSON object, if any. */
      fields: {
        [key: string]: unknown;
      };
      /** @description Source file, if available. */
      file?: string | null;
      /** @description Span id. */
      id: components["schemas"]["DbId"];
      /** @description Severity level. */
      level: components["schemas"]["LevelResponse"];
      /**
       * Format: int32
       * @description Source line, if available.
       */
      line?: number | null;
      /** @description Span name. */
      name: string;
      parent_id?: null | components["schemas"]["DbId"];
      /**
       * Format: date-time
       * @description When the span started.
       */
      started_at: string;
      /** @description Module path that created the span. */
      target: string;
    };
    /**
     * @description Sort direction shared by list endpoints.
     * @enum {string}
     */
    OrderParam: "asc" | "desc";
    /** @description A page of results plus the cursors for the neighbouring pages. */
    Page_ArtifactSummaryResponse: {
      /** @description The rows in this page. */
      items: {
        /** @description Content digest of the newest version. */
        digest: string;
        /**
         * Format: date-time
         * @description When the newest version was downloaded.
         */
        downloaded_at: string;
        /** @description Logical artifact key. */
        key: string;
        /**
         * Format: int64
         * @description Stored blob size of the newest version, in bytes.
         */
        size_bytes: number;
        /** @description Where the newest version came from. */
        source: string;
        /** @description Human-readable version of the newest version, if known. */
        version?: string | null;
        /**
         * Format: int64
         * @description How many versions of this key are stored.
         */
        version_count: number;
      }[];
      /** @description Cursor to pass as `?cursor=` for the next page. Null at the end. */
      next_cursor?: string | null;
      /** @description Cursor to pass as `?cursor=` for the previous page. Null at the start. */
      prev_cursor?: string | null;
    };
    /** @description A page of results plus the cursors for the neighbouring pages. */
    Page_ArtifactVersionResponse: {
      /** @description The rows in this page. */
      items: {
        /** @description Content digest of the stored blob. */
        digest: string;
        /**
         * Format: date-time
         * @description When this version was downloaded.
         */
        downloaded_at: string;
        /** @description Logical artifact key. */
        key: string;
        /** @description OCI media type, if applicable. */
        media_type?: string | null;
        /**
         * Format: int64
         * @description Stored blob size in bytes.
         */
        size_bytes: number;
        /** @description Where this version came from. */
        source: string;
        /**
         * Format: date-time
         * @description When this version was last verified, if ever.
         */
        verified_at?: string | null;
        /** @description Human-readable version, if known. */
        version?: string | null;
      }[];
      /** @description Cursor to pass as `?cursor=` for the next page. Null at the end. */
      next_cursor?: string | null;
      /** @description Cursor to pass as `?cursor=` for the previous page. Null at the start. */
      prev_cursor?: string | null;
    };
    /** @description A page of results plus the cursors for the neighbouring pages. */
    Page_LogEventResponse: {
      /** @description The rows in this page. */
      items: {
        /**
         * Format: uuid
         * @description Boot session this event belongs to, if known.
         */
        boot_id: string;
        /** @description Structured fields as a JSON object, if any. */
        fields: {
          [key: string]: unknown;
        };
        /** @description Source file, if available. */
        file?: string | null;
        /** @description Event id. */
        id: components["schemas"]["DbId"];
        /** @description Severity level. */
        level: components["schemas"]["LevelResponse"];
        /**
         * Format: int32
         * @description Source line, if available.
         */
        line?: number | null;
        /** @description Human-readable message, if any. */
        message?: string | null;
        span_id?: null | components["schemas"]["DbId"];
        /** @description Module path that emitted the event. */
        target: string;
        /**
         * Format: date-time
         * @description When the event was emitted.
         */
        timestamp: string;
      }[];
      /** @description Cursor to pass as `?cursor=` for the next page. Null at the end. */
      next_cursor?: string | null;
      /** @description Cursor to pass as `?cursor=` for the previous page. Null at the start. */
      prev_cursor?: string | null;
    };
    /** @description A page of results plus the cursors for the neighbouring pages. */
    Page_LogSpanResponse: {
      /** @description The rows in this page. */
      items: {
        /**
         * Format: date-time
         * @description When the span ended, if it did.
         */
        ended_at?: string | null;
        /** @description Span fields as a JSON object, if any. */
        fields: {
          [key: string]: unknown;
        };
        /** @description Source file, if available. */
        file?: string | null;
        /** @description Span id. */
        id: components["schemas"]["DbId"];
        /** @description Severity level. */
        level: components["schemas"]["LevelResponse"];
        /**
         * Format: int32
         * @description Source line, if available.
         */
        line?: number | null;
        /** @description Span name. */
        name: string;
        parent_id?: null | components["schemas"]["DbId"];
        /**
         * Format: date-time
         * @description When the span started.
         */
        started_at: string;
        /** @description Module path that created the span. */
        target: string;
      }[];
      /** @description Cursor to pass as `?cursor=` for the next page. Null at the end. */
      next_cursor?: string | null;
      /** @description Cursor to pass as `?cursor=` for the previous page. Null at the start. */
      prev_cursor?: string | null;
    };
    /** @description A page of results plus the cursors for the neighbouring pages. */
    Page_TaskResponse: {
      /** @description The rows in this page. */
      items: {
        /**
         * Format: date-time
         * @description When the invocation was recorded.
         */
        created_at: string;
        /** @description Failure detail, if any. */
        error?: string | null;
        /**
         * Format: date-time
         * @description When it finished, if it did.
         */
        finished_at?: string | null;
        /** @description Invocation id. */
        id: components["schemas"]["DbId"];
        /** @description The input the task was created with. */
        input: unknown;
        /** @description The kind of task. */
        kind: string;
        /** @description The output, once the task succeeds. */
        output?: unknown;
        parent_id?: null | components["schemas"]["DbId"];
        progress?: null | components["schemas"]["ProgressResponse"];
        /**
         * Format: date-time
         * @description When it started running, if it did.
         */
        started_at?: string | null;
        /** @description Lifecycle state. */
        status: components["schemas"]["TaskStatusResponse"];
      }[];
      /** @description Cursor to pass as `?cursor=` for the next page. Null at the end. */
      next_cursor?: string | null;
      /** @description Cursor to pass as `?cursor=` for the previous page. Null at the start. */
      prev_cursor?: string | null;
    };
    /** @description A localizable progress message: a translation key and its arguments. */
    ProgressMessageResponse: {
      /** @description Arguments to interpolate into the resolved message. */
      args: {
        [key: string]: string;
      };
      /** @description Translation key for the current step. */
      key: string;
    };
    /** @description Live progress of a running task. */
    ProgressResponse: {
      /**
       * Format: int64
       * @description Units of work completed so far.
       */
      done?: number | null;
      message?: null | components["schemas"]["ProgressMessageResponse"];
      /**
       * Format: int64
       * @description Total units of work expected, if known.
       */
      total?: number | null;
    };
    /** @description A registered task kind, with its capabilities and JSON Schemas. */
    TaskDefinitionResponse: {
      /** @description Whether the kind can be cancelled. */
      cancellable: boolean;
      /** @description JSON Schema of the kind's input. */
      input_schema: unknown;
      /** @description The kind string. */
      kind: string;
      /** @description JSON Schema of the kind's output. */
      output_schema: unknown;
      /** @description Whether the kind is safe to interrupt across a restart. */
      resumable: boolean;
    };
    /** @description One task invocation, returned by the task endpoints. */
    TaskResponse: {
      /**
       * Format: date-time
       * @description When the invocation was recorded.
       */
      created_at: string;
      /** @description Failure detail, if any. */
      error?: string | null;
      /**
       * Format: date-time
       * @description When it finished, if it did.
       */
      finished_at?: string | null;
      /** @description Invocation id. */
      id: components["schemas"]["DbId"];
      /** @description The input the task was created with. */
      input: unknown;
      /** @description The kind of task. */
      kind: string;
      /** @description The output, once the task succeeds. */
      output?: unknown;
      parent_id?: null | components["schemas"]["DbId"];
      progress?: null | components["schemas"]["ProgressResponse"];
      /**
       * Format: date-time
       * @description When it started running, if it did.
       */
      started_at?: string | null;
      /** @description Lifecycle state. */
      status: components["schemas"]["TaskStatusResponse"];
    };
    /**
     * @description Filter for task status, including the `active` and `finished` groups.
     * @enum {string}
     */
    TaskStatusParam:
      | "active"
      | "finished"
      | "pending"
      | "running"
      | "succeeded"
      | "failed"
      | "cancelled"
      | "interrupted";
    /**
     * @description Lifecycle state of a task invocation.
     * @enum {string}
     */
    TaskStatusResponse:
      "pending" | "running" | "succeeded" | "failed" | "cancelled" | "interrupted";
    /** @description Version information returned by `GET /api/v1/version`. */
    VersionResponse: {
      /** @description Version of the Aperture gateway. */
      aperture: string;
      /**
       * Format: uuid
       * @description Unique id of this gateway boot session.
       */
      boot_id: string;
    };
    /**
     * @description Field a version listing is sorted by.
     * @enum {string}
     */
    VersionSortParam: "downloaded_at" | "size_bytes";
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  listArtifacts: {
    parameters: {
      query?: {
        /** @description Maximum rows to return. Defaults to 50. */
        limit?: number;
        /** @description Cursor from a page's `next_cursor` or `prev_cursor`. */
        cursor?: string;
        /** @description Sort direction. */
        order?: components["schemas"]["OrderParam"];
        /** @description Match keys containing this substring. */
        q?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Artifacts */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Page_ArtifactSummaryResponse"];
        };
      };
    };
  };
  getArtifact: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Artifact key */
        key: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Artifact */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ArtifactSummaryResponse"];
        };
      };
      /** @description Unknown artifact */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  listArtifactVersions: {
    parameters: {
      query?: {
        /** @description Maximum rows to return. Defaults to 50. */
        limit?: number;
        /** @description Cursor from a page's `next_cursor` or `prev_cursor`. */
        cursor?: string;
        /** @description Sort direction. */
        order?: components["schemas"]["OrderParam"];
        /** @description Field to sort by. Defaults to downloaded time. */
        sort?: components["schemas"]["VersionSortParam"];
        /** @description Only versions with this exact media type. */
        media_type?: string;
        /** @description Only versions with this exact version string. */
        version?: string;
      };
      header?: never;
      path: {
        /** @description Artifact key */
        key: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Versions */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Page_ArtifactVersionResponse"];
        };
      };
    };
  };
  getArtifactVersion: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Artifact key */
        key: string;
        /** @description Content digest */
        digest: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Version */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ArtifactVersionResponse"];
        };
      };
      /** @description Unknown version */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  deleteArtifactVersion: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Artifact key */
        key: string;
        /** @description Content digest */
        digest: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Version evicted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unknown version */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  listLogs: {
    parameters: {
      query?: {
        /** @description Maximum rows to return. Defaults to 50. */
        limit?: number;
        /** @description Cursor from a page's `next_cursor` or `prev_cursor`. */
        cursor?: string;
        /** @description Sort direction. Defaults to descending (newest first). */
        order?: components["schemas"]["OrderParam"];
        /** @description Only events at this severity or higher. */
        min_level?: components["schemas"]["LevelResponse"];
        /**
         * @description Only events whose target is one of these (comma-separated). Example:
         *     `aperture,aperture_http`.
         */
        target?: string[];
        /** @description Substring search across message and target. */
        q?: string;
        /** @description Only events belonging to this span. */
        span_id?: components["schemas"]["DbId"];
        /** @description Only events from this boot session. */
        boot_id?: string;
        /** @description Only events at or after this time (RFC 3339). */
        since?: string;
        /** @description Only events at or before this time (RFC 3339). */
        until?: string;
        /** @description Structured field filter as a JSON object, e.g. `{"key":"value"}`. */
        fields?: components["schemas"]["JsonQueryString"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Log events */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Page_LogEventResponse"];
        };
      };
    };
  };
  listLogBoots: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Boot sessions */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BootResponse"][];
        };
      };
    };
  };
  listSpans: {
    parameters: {
      query?: {
        /** @description Maximum rows to return. Defaults to 50. */
        limit?: number;
        /** @description Cursor from a page's `next_cursor` or `prev_cursor`. */
        cursor?: string;
        /** @description Sort direction. Defaults to descending (newest first). */
        order?: components["schemas"]["OrderParam"];
        /** @description Only spans at this severity or higher. */
        min_level?: components["schemas"]["LevelResponse"];
        /**
         * @description Only spans whose target is one of these (comma-separated). Example:
         *     `aperture,aperture_storage`.
         */
        target?: string[];
        /** @description Only spans from this boot session. */
        boot_id?: string;
        /** @description Only spans started at or after this time (RFC 3339). */
        since?: string;
        /** @description Only spans started at or before this time (RFC 3339). */
        until?: string;
        /** @description Only direct children of this span id. */
        parent_id?: components["schemas"]["DbId"];
        /** @description When true, only root spans (no parent) are returned. */
        parent_null?: boolean;
        /** @description Structured field filter as a JSON object, e.g. `{"key":"value"}`. */
        fields?: components["schemas"]["JsonQueryString"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Spans */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Page_LogSpanResponse"];
        };
      };
    };
  };
  getSpan: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Span id */
        id: components["schemas"]["DbId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Span with events */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LogSpanDetailResponse"];
        };
      };
      /** @description Unknown span */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  listLogTargets: {
    parameters: {
      query?: {
        /** @description Only targets starting with this prefix. */
        q?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Target names */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": string[];
        };
      };
    };
  };
  listTaskDefinitions: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Task definitions */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskDefinitionResponse"][];
        };
      };
    };
  };
  listTasks: {
    parameters: {
      query?: {
        /** @description Maximum rows to return. Defaults to 50. */
        limit?: number;
        /** @description Cursor from a page's `next_cursor` or `prev_cursor`. */
        cursor?: string;
        /** @description Sort direction. */
        order?: components["schemas"]["OrderParam"];
        /** @description Only tasks in this state, or the `active`/`finished` groups. */
        status?: components["schemas"]["TaskStatusParam"];
        /** @description Only tasks of this kind. */
        kind?: string;
        /** @description Only children of this task. */
        parent?: components["schemas"]["DbId"];
        /** @description Only top-level tasks (no parent). Ignored when `parent` is set. */
        root?: boolean;
        /**
         * @description Only tasks whose input JSON has `input_value` at this path, for example
         *     `key` or `source.reference`. Requires `input_value`.
         */
        input_path?: string;
        /** @description The value the field at `input_path` must equal. */
        input_value?: string;
        /**
         * @description Only tasks whose output JSON has `output_value` at this path. Requires
         *     `output_value`.
         */
        output_path?: string;
        /** @description The value the field at `output_path` must equal. */
        output_value?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Tasks */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Page_TaskResponse"];
        };
      };
    };
  };
  createTask: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateTaskInput"];
      };
    };
    responses: {
      /** @description Task created */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskResponse"];
        };
      };
      /** @description Unknown kind or invalid input */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getTask: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Task id */
        id: components["schemas"]["DbId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Task */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskResponse"];
        };
      };
      /** @description Unknown task */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  cancelTask: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Task id */
        id: components["schemas"]["DbId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Cancellation requested */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unknown task */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Task kind cannot be cancelled */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Task has already finished */
      410: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getGatewayVersion: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Gateway version */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["VersionResponse"];
        };
      };
    };
  };
}
